### ISSUE TITLE
Doesn't work with mailer layout?

### ISSUE THREAD

**Issue by aug-riedinger** [schneems/maildown#17]
I have the following code:

```
class UserMailer < ActionMailer::Base
  default template_path: 'mailers/user'
  layout 'mailers/layouts/default'

  def my_mailer
    mail(subject: 'Hello world').deliver
  end
end
```

And `views/mailers/user/my_mailer.md.erb` along with `views/mailers/layouts/default.html.erb` and `views/mailers/layouts/default.text.erb`.

I would expect those `layouts` to wrap my templates, but it actually doesn't.

It should, shouldn't it? Any idea why? If I have time to investigate on this, any tip on where I should start looking at?

**Comment by schneems** [comment]
Duplicate issue: https://github.com/schneems/maildown/issues/9

You need a `default.md.erb` template

**Comment by aug-riedinger** [comment]
Thanks for coming back.

First, I think this should be mentioned in the doc, if you don't want further issue duplication.

Second, I tried that, and it did not work as expected. After some code investigations, I found that there are two types of handlers: 
- final handlers: `default_formats`, which you register [here](https://github.com/schneems/maildown/blob/master/lib/maildown/ext/action_mailer.rb) and tells `ActionMailer` (could probably be `ActionView`) that tells rails `.md` can be a a final extension (`filename.md.other_preprocessors`)
- template handlers: `ActionView::Template.register_template_handler` that tells rails `.md` can be a template handler.

At the end, I used the solution suggested by this SO post: http://stackoverflow.com/a/10131299/1620081

```
require 'rdiscount'

module MarkdownHandler
  def self.erb
    @erb ||= ActionView::Template.registered_template_handler(:erb)
  end

  def self.call(template)
    compiled_source = erb.call(template)
    "RDiscount.new(begin;#{compiled_source};end).to_html"
  end
end

ActionView::Template.register_template_handler :md, MarkdownHandler
```

It handles views in the format `filename.html.md` (much like [markerb](https://github.com/plataformatec/markerb), but I find the markerb extension ugly). It doesn't completely works as expected (the best would be `filename.html.md.erb` to be really logical, which I read somewhere is not possible), but at least handles:

- layouts: default.html.md
- views: mail_action.html.md

Well, that being said, my question is:

> Shouldn't be combined in the gem the template handler availability and final handler, so that both can work out of the box?

I have been trying things around, but without success, my knowledge in the `ActionView` world is too low.

But if you want to make a beautifully featured gem (which IMHO should be defaulted into rails), it could be worth it integrating it, wouldn't it?

Thanks for consideration and making the gem available anyway.

**Comment by schneems** [comment]
>  I think this should be mentioned in the doc

:boom: genius, can you give me a doc PR? 

> IMHO should be defaulted into rails

My biggest problem with markdown email templates is that you can't follow regular code indentation. For example

```
<% @assignments.each do |assignment| %>
### <%= "##{assignment.issue.number}" if assignment.issue.number %> <%= link_to assignment.issue.title, issue_click_url(assignment.id, assignment.user.id ) %>

<%= "[#{assignment.repo.full_name}](#{repo_url(assignment.repo)})" %>
<%= time_ago_in_words assignment.issue.last_touched_at %> ago
```

Since if you correctly indented it

```
<% @assignments.each do |assignment| %>
  ### <%= "##{assignment.issue.number}" if assignment.issue.number %> <%= link_to assignment.issue.title, issue_click_url(assignment.id, assignment.user.id ) %>

  <%= "[#{assignment.repo.full_name}](#{repo_url(assignment.repo)})" %>
  <%= time_ago_in_words assignment.issue.last_touched_at %> ago
```

Markdown doesn't ignore that whitespace, but may treat this as a block quote, especially when there are multiple nested blocks. 

I've been thinking about this recently and maybe it makes sense to ignore block quotes based on indentation all together. Only support the `>` block quote style. I think that's probably what most people want but it's a huge breaking change, i'm not sure how difficult it would be to implement it either.

> Shouldn't be combined in the gem the template handler availability and final handler, so that both can work out of the box?

I don't know. I'm not a huge fan of the filename based features (even though I wrote this). I.e. if you name your file `myfile.md.erd` it won't work, you won't get an error, and it's really hard to debug :(. In an ideal world the template engine would understand valid extension combinations, and when it can't find one would raise a meaningful or helpful error. To me the two extensions `md.erb` mean different things from `erb.md`. In rails convention you could say `.html.erb` or `.text.erb` which essentially seems to work backwards, rendering the ERB first. So, maybe we can make this better in Rails and lay the groundwork for markdown emails but ActionView is a BEAST to work with and is extremely performance sensitive. I honestly don't know how I would open up an API to make maildown not rely on monkeypatching.

**Comment by aug-riedinger** [comment]
I've retried with:
- layout: `layout.md.erb`
- template: `template.md.erb`

The layout is somewhat correctly displayed (only the `<!DOCTYPE html>` is parsed as a string), but the template content is not parsed as Markdown, though the `.erb` processing is applied.

So I've found my way around by doing in  `layout.md.erb`:

```
<%= Kramdown::Document.new(yield).to_html.html_safe %>
```

Is this the way you'd suggest to do this?

I wish I had more time to investigate on the whole `ActionView` topic, my intuition tells me it would be a great topic to work on, and I really advocate using markdown to write inline html text content.
