### ISSUE TITLE
Treat kramdown as an optional dependency?

### ISSUE THREAD

**Issue by MarcusRiemer** [schneems/maildown#49]
I use `maildown` with the `redcarpet` renderer, but because `maildown` depends on `kramdown` bundler insists on installing both gems. As far as I am aware this is ultimately a shortcoming of `bundler` itself: It does not support optional dependencies or allows me to override dependencies.

As far as I know the "normal" way of handling this is to **not** specify these "sort of optional" dependencies at the gem level. Rails for example does not specify all sorts of database drivers, although at least one of them will have to be used. Would you consider to do the same for maildown?

**Comment by schneems** [comment]
I opened this issue some years ago https://github.com/rubygems/rubygems/issues/1811

> Would you consider to do the same for maildown?

The usual pattern is to include the default gem so that it works out of the box. If you removed the kramdown requirement then people who's apps had been working would break as most of them likely are not specifying to include `kramdown` as well.

Even worse, it likely wouldn't be caught until production time, since many people do not render or view emails in development. Lots don't actually test rendering of emails either.

I would not accept removing kramdown as a dependency, however if there's a patch to perhaps defer requiring kramdown so it doesn't get loaded in memory somehow, I might be open to it.
